# ==============================================================================
# Pytest Configuration File
# ==============================================================================

[pytest]
pythonpath = .
testpaths = tests
